---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: microbot-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: phpmyadmin.swan-blanc.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: phpmyadmin-service
              servicePort: 80