kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
    name: docker-registry-secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:6xRNGNcInsmzfUYsRPXW0VPmnlHlV9j3+1H5XqpxiMR+X51lMPZ5gTU1JfnnZoLw1t1d6s67YjcWWSNxHIIbr+RGPd+0OaScGcXEeerDCBbF8NlJwfOFW/HrBkyliUkfGd16p/HkjohiLx7/llr1BhUrZFr8uSdO4nZdn7qPODfK55ArcgaDTw==,iv:DHffc8mMVXtRRMOMZrBxqqUgMa/Hjfznv//gx6YoaSw=,tag:LUWH0eMiGUR8Bk6MxDeh4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-02T08:35:19Z"
    mac: ENC[AES256_GCM,data:MVE9LPTPj47EfwLKvpItI0VpIqk3Q+itQid3i62eICk6gyips8nmzGEY8rgQ/mUQTHCGxsQc1HxoJL8f1Vp5P98FXxFVsAIkmerBy4pCfT1nWh+OOZFNi6XDOoyueMIiElQUw8zI+BFl8xEGbAEfDBBVvF3WRtpOhNlFbFqG/R8=,iv:y9T3CQ+P8iEN1MjwUErufJxivrQ5cp3z2kH/cLgkzSY=,tag:VAFLoKZbzqEdGhfomjXnBA==,type:str]
    pgp:
        - created_at: "2021-05-02T08:35:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwxOKjk2X06RAQwAhrNWXXr8Nf6ByeNT751KUBh2Fkv6M4oY5UdycVIRWg2+
            AfOvU+CXzOCBVGeUJ+wS1sSvqbIGNz/8U8SKlH55VqLCe9wyDBVoapfJzn4OCCvm
            9w0K1mpBVYBEeOkoV7P1sh60qOMp+xCXoIAQTxJ0/hWntRUUkgoWceX2uRIy8KzU
            Wx51pYbGjTxeryXCl9LXxaXNveSvHbtwchJvEJ3pdShSk/KmBkuI49YHPIRoEIFx
            PUv+BXmr083Y+bRzfupb3eW+5w8+IIhr6pAHOOzHvfh3fdFNtw3hQ2NG/YkXhqUF
            lzHiCWr80mXm+eRb4JJBXM+pOCYExATw40AE1xCjuy2ZfqZ3kU/f50vUq84dlfc8
            UmSFUnaiM0Kv9tfF6d9WJmd0E+PyYW9L4YnZbqDnD3m+GLQm3K3esb1vAeYuHEiI
            3SXY8O8nIGdAH50DAY3/f+JOhBkDdHH52EhdQ+gMkit/d3vBSjwIIBHzGFg7pyDp
            T34ylngqL3eXXccmZdmG0lwBiy8cgQFSpgxj/233VjqMV/PHVR6keyzHxxX5ca7A
            ujkXixZH0vfRdcmPtLB0qsCj+Z5pNSjpUrgdWZZJ+Z5mk97DyHYLFgHx+gosVMrW
            ioSKYo7fexsGeyQJ/w==
            =0sCZ
            -----END PGP MESSAGE-----
          fp: 123BA4DCEEA4BED6ED5A4CE2BFB073CD386661F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
