apiVersion: v1
kind: Secret
metadata:
    name: secrets
type: Opaque
data:
    root-password: ENC[AES256_GCM,data:4aKD3Mh733v2h50XusiZ92qAM6b0R/Y2cGOOjrv0QCXRz0Z4EJeVdrAlFpK7allW,iv:+SjfPkHl77PN6S6vSm7BZ6YxM0udNTVBtCNMjplkLpM=,tag:548wWMLTTqlYnAE3YJR+RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-02T08:35:19Z"
    mac: ENC[AES256_GCM,data:EtfQpHGoXNT8HNIICC241otyjFEZ3+A/fLhcux7G8Nr2KDM/XoCqN/TgPBphVfpnG4p3frkh5rhX3uC+57AnsKq9wOrCN0C0t4mwS92a8NySFVxg3Zzi9PRGWenmFiQdo5RvFK1RjDSQSipJDHBm6ra6wpy7Z+MDIzmb0IOCAJI=,iv:QENY+crW/kolr23twQFbiKRAsHkU8VmI9uRZpvb3/ZY=,tag:blqiS/E8p/EuhFqXAn1+UQ==,type:str]
    pgp:
        - created_at: "2021-05-02T08:35:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwxOKjk2X06RAQv/S6rpEf4dlJAYRpRBR6fu8XUncSMUvN8Jy6V9NJgdXnn6
            LqiK6P4XwodMPOXt9z+WiRU4JNHohgwXU0NE8rXx5I+u54z//x+t2lJEsseJyq2Y
            dymYvwhsJnrRerNPNKMyuE8Edgubo7AC5jfCpX+CFxER7z1ipwyxG4bT5lpzp5nj
            Orcle1mWd3NbSqtENVMXHGRr23QNQKXImuKdI6xJ/vrQWAlKP0mWJu+AC1lNKqmv
            uC8m2YLjRNz4gfgcWCrQXP0In2FwHrLRFijDh3v/ISWfrgWsrr/QAjL3CcOA39w4
            CwH3wANNPSO03Eu+Q+KpqfCFtNkf7FnCJpsKFaoZ8pntdnfymZrcRey48ic9wQdk
            8s1bnQ6VpWpA77uJ/iaIcvgl4T4FGFXKAcfWTZfqlxylhQpKsJ5YCcPLsNxTv/j/
            JXLDCcG26+h4+zWc3c42b3YtYT4WIJuGolr5781gygqGuJ8bkgZRJr8hfMBwIYLH
            +fuUd/yosxfL9G7vMdko0l4BR4VVrxZ/Iq0QD3Y2QlY7Drdeiz3la39MQ0Op1S1I
            lqgBsD90LQKb3x935gx+Q+Ryo6j7IWdfHDU3BmITR0ibtcH/GH7GSaPuj5adaILU
            k2jLSMCGdAHtIUywKfLr
            =aMx7
            -----END PGP MESSAGE-----
          fp: 123BA4DCEEA4BED6ED5A4CE2BFB073CD386661F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
