---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-server
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cloud.swan-blanc.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api-server
              servicePort: 80
